<a href="https://colab.research.google.com/github/abhishek-marathe04/learning-pytorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Create a random tensor with shape (7, 7).
tensor_A = torch.rand(size=(7,7))
tensor_A

tensor([[0.5223, 0.0700, 0.4406, 0.2575, 0.3150, 0.4854, 0.8270],
        [0.3386, 0.6848, 0.0819, 0.3324, 0.5929, 0.2016, 0.9951],
        [0.3618, 0.5332, 0.8610, 0.6281, 0.4496, 0.8858, 0.7725],
        [0.4522, 0.2302, 0.8442, 0.9382, 0.5386, 0.5855, 0.3740],
        [0.8802, 0.0652, 0.7543, 0.8809, 0.3126, 0.0939, 0.7747],
        [0.7679, 0.7532, 0.6296, 0.5310, 0.7331, 0.9350, 0.3860],
        [0.6745, 0.8014, 0.1204, 0.5353, 0.7845, 0.4766, 0.8763]])

In [3]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

tensor_B = torch.rand(size=(1,7))
tensor_B

tensor([[0.5344, 0.3939, 0.6466, 0.1791, 0.8015, 0.3821, 0.7253]])

In [5]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.6755],
        [1.8373],
        [2.3317],
        [1.9728],
        [1.9899],
        [2.4341],
        [2.2964]])

In [6]:
# Set the random seed to 0 and do exercises 2 & 3 over again.

In [7]:
seed = torch.manual_seed(0)
tensor_A = torch.rand(size=(7,7))
tensor_A

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [8]:
seed = torch.manual_seed(0)
tensor_B = torch.rand(size=(1,7))

torch.matmul(tensor_A, tensor_B.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [9]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed()
# but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

seed = torch.cuda.manual_seed(1234)

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [12]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

seed = torch.cuda.manual_seed(1234)

tensor_A_on_gpu = torch.rand(size=(2,3), device=device)

seed = torch.cuda.manual_seed(1234)
tensor_B_on_gpu = torch.rand(size=(2,3), device=device)

tensor_A_on_gpu, tensor_B_on_gpu

(tensor([[0.8964, 0.4556, 0.6323],
         [0.3489, 0.4017, 0.0223]]),
 tensor([[0.1689, 0.2939, 0.5185],
         [0.6977, 0.8000, 0.1610]]))

In [15]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
mat_mul = torch.matmul(tensor_A_on_gpu, tensor_B_on_gpu.T)
mat_mul

tensor([[0.6131, 1.0917],
        [0.1886, 0.5684]])

In [17]:
mat_mul.max(), mat_mul.min()

(tensor(1.0917), tensor(0.1886))

In [19]:
mat_mul.argmax(), mat_mul.argmin()

(tensor(1), tensor(2))

In [22]:
torch.manual_seed(7)
tensor_C = torch.rand(size=[1,1,1,10])
tensor_C

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [23]:
tensor_D = torch.squeeze(tensor_C)
tensor_D

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])