<a href="https://colab.research.google.com/github/abhishek-marathe04/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch fundamentals

In [1]:
print("Hello from python")

Hello from python


In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.9.0+cpu


# Introduction to tensor

Creating Tensor

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
# Random tensors

RANDOM_TENSOR = torch.rand(1,10,4)

RANDOM_TENSOR

tensor([[[0.8240, 0.2812, 0.0143, 0.1849],
         [0.6555, 0.2173, 0.4416, 0.5582],
         [0.4662, 0.5261, 0.1331, 0.4806],
         [0.8198, 0.5915, 0.1157, 0.1167],
         [0.5743, 0.0454, 0.3871, 0.7454],
         [0.5896, 0.6015, 0.8085, 0.9886],
         [0.8491, 0.9354, 0.5097, 0.4928],
         [0.5374, 0.1361, 0.8307, 0.7014],
         [0.2178, 0.1050, 0.3284, 0.8652],
         [0.4839, 0.7319, 0.9368, 0.3962]]])

In [19]:
RANDOM_TENSOR.ndim

3

In [20]:
RANDOM_TENSOR.shape

torch.Size([1, 10, 4])

In [21]:
# Create a random tensor with similar size of image
random_image_size_tensor = torch.rand(3,224,224) # First is colour_channels, second is height, third dimenstion is width

Zeros and Ones

In [22]:
zeros = torch.zeros(4,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(7,6))

ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [24]:
ones.ndim

2

In [25]:
ones.dtype

torch.float32

Creating tensor range and tensor-like

In [29]:
one_to_ten = torch.arange(start=0, end=11, step=2)

In [30]:
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [31]:
zeros_like_test = torch.zeros_like(one_to_ten)

In [32]:
zeros_like_test

tensor([0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note : Tensor datatypes is one of the 3 big errors
1. Tensor not right dtype
2. not right size
3. tensors are not on right device

In [35]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # It can be cpu, cuda ,what device your tensor on
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
int_64_tensor = torch.tensor([3,6,8], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 8])

In [40]:
int_64_tensor * float_16_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

In [41]:
int_64_tensor @ float_16_tensor

RuntimeError: dot : expected both vectors to have same dtype, but found Long and Half