<a href="https://colab.research.google.com/github/abhishek-marathe04/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch fundamentals

In [43]:
print("Hello from python")

Hello from python


In [44]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.9.0+cpu


# Introduction to tensor

Creating Tensor

In [45]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [46]:
scalar.ndim

0

In [47]:
scalar.item()

7

In [48]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [49]:
vector.ndim

1

In [50]:
vector.shape

torch.Size([2])

In [51]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [52]:
matrix.ndim

2

In [53]:
matrix[0]

tensor([7, 8])

In [54]:
matrix.shape

torch.Size([2, 2])

In [55]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [56]:
TENSOR.ndim

3

In [57]:
TENSOR.shape

torch.Size([1, 3, 3])

In [58]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [59]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
# Random tensors

RANDOM_TENSOR = torch.rand(1,10,4)

RANDOM_TENSOR

tensor([[[0.9875, 0.0450, 0.1516, 0.9992],
         [0.0593, 0.4979, 0.3070, 0.0906],
         [0.3987, 0.3156, 0.8549, 0.6399],
         [0.6300, 0.3112, 0.5348, 0.0693],
         [0.7881, 0.1479, 0.7494, 0.4283],
         [0.7689, 0.5596, 0.2253, 0.8662],
         [0.0968, 0.8343, 0.9908, 0.7056],
         [0.4329, 0.3652, 0.4962, 0.7210],
         [0.7407, 0.9362, 0.6669, 0.7466],
         [0.1997, 0.7855, 0.0204, 0.6953]]])

In [61]:
RANDOM_TENSOR.ndim

3

In [62]:
RANDOM_TENSOR.shape

torch.Size([1, 10, 4])

In [63]:
# Create a random tensor with similar size of image
random_image_size_tensor = torch.rand(3,224,224) # First is colour_channels, second is height, third dimenstion is width

Zeros and Ones

In [64]:
zeros = torch.zeros(4,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [65]:
ones = torch.ones(size=(7,6))

ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [66]:
ones.ndim

2

In [67]:
ones.dtype

torch.float32

Creating tensor range and tensor-like

In [68]:
one_to_ten = torch.arange(start=0, end=11, step=2)

In [69]:
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [70]:
zeros_like_test = torch.zeros_like(one_to_ten)

In [71]:
zeros_like_test

tensor([0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note : Tensor datatypes is one of the 3 big errors
1. Tensor not right dtype
2. not right size
3. tensors are not on right device

In [72]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # It can be cpu, cuda ,what device your tensor on
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype

torch.float32

In [74]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [75]:
int_64_tensor = torch.tensor([3,6,8], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 8])

In [76]:
int_64_tensor * float_16_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

In [77]:
# Create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [78]:
tensor * 10

tensor([10, 20, 30])

In [79]:
tensor - 5

tensor([-4, -3, -2])

In [80]:
# in built

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [81]:
torch.add(tensor, 19)

tensor([20, 21, 22])

In [82]:
torch.matmul(tensor, tensor)

tensor(14)

### One of the main common errors is shape errors

Two main rules that matrix multiplication needs to satisfy

1. The inner dimensions must match

* `(3,2) @ (3,2)` -> Wont work
* `(2,3) @ (3,2)` -> will work
* `(3,2) @ (2,3)` -> Will work

2. The resulting matrix has the shape of the **outer dimensions** :
* `(2,3) @ (3,2)` -> `(2,2)`
* `(10,3) @ (3,10)` -> `(3,3)`

In [83]:
# Shapes

tensor_A = torch.tensor([[1,2,3],
                         [4,5,6]])

tensor_B = torch.tensor([[1,2,3],
                         [4,5,6]])


In [84]:
#This wont work as it does not satisfy rules
# torch.matmul(tensor_A, tensor_B)

In [85]:
# Lets try to take transpose of one, that will work
print(tensor_A.shape, tensor_B.shape)

print(tensor_A, tensor_B.T)


torch.Size([2, 3]) torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]]) tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [86]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[14, 32],
        [32, 77]])

## Finding the min, max, mean, sum etc

In [87]:
x = torch.arange(1,100, 9, dtype=torch.float32)
print(x)
x.dtype

tensor([ 1., 10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])


torch.float32

In [88]:
torch.max(x), x.max()

(tensor(91.), tensor(91.))

In [89]:
torch.min(x), x.min()

(tensor(1.), tensor(1.))

In [90]:
torch.mean(x), x.mean()

(tensor(46.), tensor(46.))

## Find poostional min and max

In [91]:
x

tensor([ 1., 10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [92]:
x.argmin()

tensor(0)

In [93]:
x[0]

tensor(1.)

In [94]:
x.argmax()

tensor(10)

In [95]:
x[10]

tensor(91.)

## Reshaping, stacking, squeezing and unsqeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
* Sqeeze - removes all `1` dimensions from the tensor
* Unsqeeze - add a `1` dimensions to target tensor
* Permute - Return a view of the input with dimensions permuted (swap) in certain way

In [96]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [97]:
# Add an extra dimention
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [98]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [99]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [100]:
# Change the view
z = x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [101]:
# Changing z changes x coz view of tensor shares same memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [102]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [103]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [104]:
# torch squeeze
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [105]:
x_zeros = torch.zeros(2, 1)
x_zeros, x_zeros.shape

(tensor([[0.],
         [0.]]),
 torch.Size([2, 1]))

In [106]:
x_squeezed = torch.squeeze(x_zeros)
x_squeezed, x_squeezed.shape

(tensor([0., 0.]), torch.Size([2]))

In [107]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[0.],
         [0.]]),
 torch.Size([2, 1]))

In [108]:
x_squeezed

tensor([0., 0.])

In [109]:
x_zeros

tensor([[0.],
        [0.]])

In [110]:
x_permuted = torch.permute(x_zeros, dims=(1,0))
x_permuted

tensor([[0., 0.]])

In [111]:
x_original = torch.rand(size=(224,224,4))

# Permute
x_permuted = x_original.permute(2,0,1) # shifts axis 0 > 1, 1 -> 2, 2 -> 0
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 4]), torch.Size([4, 224, 224]))

In [112]:
x_original[0,0,0]

tensor(0.5694)

In [113]:
x_original[0,0,0] = 0.432

In [114]:
x_permuted[0,0,0]

tensor(0.4320)

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [115]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [116]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [117]:
x[0][0]

tensor([1, 2, 3])

In [118]:
x[0][0][0]

tensor(1)

In [119]:
# You can use : to get all of target
x[:, 0]

tensor([[1, 2, 3]])

In [120]:
# Get all values of 0th and 1st butt only index 1 of 2nd
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors & numpy



In [121]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

### Change the value of array, what will this do to `tensor`?

In [122]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [123]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [124]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))